jenkins:
  image: gentilhommefx/jenkins
  ports:
    - 8080:8080
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/var/jenkins_home:/var/jenkins_home"
    - "/tmp:/tmp"
  privileged: true
